CREATE TABLE IF NOT EXISTS applications (
                                            app_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                            app_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (app_id)
    );

CREATE TABLE IF NOT EXISTS statistics (
                                          id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          app_id INTEGER,
    uri VARCHAR NOT NULL,
    ip VARCHAR NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                            FOREIGN KEY (app_id) REFERENCES applications(app_id)
    );