version: '3.1'
services:
  stats-server-service:
    build: stats-server/stats-server-service
    container_name: stats-server-service
    ports:
      - "9091:9091"
    depends_on: [ stats-db ]
    environment:
      - DB_NAME=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server-client:
    build: stats-server/stats-server-client
    container_name: stats-server-client
    ports:
      - "9090:9090"
    depends_on: [ stats-server-service ]
    environment:
      - STATS_SERVER_SERVICE_URL=http://stats-server-service:9091

  ewm-service:
    build: ewm-service/
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on: [ stats-server-client , ewm-db ]
    environment:
      - STATS_SERVER_CLIENT_URL=http://stats-server-client:9090
      - DB_NAME=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root